### ISSUE TITLE
Create users table

### ISSUE THREAD

**Issue by rrabinovitch** [RosanneUssery/food-rescue-robot-v2#12]
**Description**
As a volunteer coordinator API, I can create a `User` record.

Acceptance criteria:
* there is a Users table that includes all columns listed in [data models spreadsheet tab](https://docs.google.com/spreadsheets/d/1a_crWi4vI0xXMI9unqz9tnbgHznfljVkGUNna_rEdCQ/edit#gid=187036189)

Additional notes:
n/a

**Comment by rrabinovitch** [comment]
process:
* added testing gems - rspec, pry, and a few others
* `docker-compose run api bundle install`
* `docker-compose run api rails g rspec:install` to install rspec
     * got various versions of these two errors:
     ```
     /usr/local/lib/ruby/3.0.0/bundler/spec_set.rb:91:in `block in materialize': Could not find pry-0.14.1 in any of the sources (Bundler::GemNotFound)

     Could not find pry-rails-0.3.9 in any of the sources
     Run `bundle install` to install missing gems.
     ```
     * running `docker-compose run api bundle update` changed the gem it was complaining about to `puma` ¯\_(ツ)_/¯
     * changed dockerfile ([reference](https://slacker.ro/2020/02/03/dockerizing-a-ruby-on-rails-application/)) bundler install line - `RUN gem install rails bundler
` - did not work so I reverted
     * removed `puma` to test out and the same type of error message appeared for whatever the next gem is on the list


**pausing here**


quetions:
* does bundle install need to be run or does that happen behind the scenes when spinning up docker? (I added these instructions to readme, but maybe it's not actually necessary)
* this seems like a docker issue, but i can't track down what it is...

**Comment by rrabinovitch** [comment]
next steps:
* [migration](https://guides.rubyonrails.org/active_record_migrations.html) to create users table: `docker compose run api rails g migration CreateUser uuid:<DATA TYPE?> password:<DATA TYPE?> username:string access_level`
     * confirm data types for `uuid` and `password` - I think these are associated with devise
     * set up access level enum values in `user` model ((reference)[https://naturaily.com/blog/ruby-on-rails-enum])




**questions:**
* does bundle install need to be run or does that happen behind the scenes when spinning up docker? (I added these instructions to readme, but maybe it's not actually necessary)

**Comment by pkuykendall** [comment]
👋 Hey! Just wanted to pop in and recommend [Devise](https://github.com/heartcombo/devise#getting-started) for managing and migrating User records. I think it would give a great starting point.

**Comment by rrabinovitch** [comment]
thanks @pkuykendall! I've got it referenced above in my notes and am mid-set up :)

**Comment by pkuykendall** [comment]
Awesome! Sorry, I didn't read through everything. Just saw the latest message in my email. I'll make sure I use my eyes next time 😆
